#define _boolean				1
#define _else					2
#define _implements				3
#define _println				4
#define _void					5
#define _multiplication			6
#define _lessequal				7
#define _notequal				8
#define _assignop				9
#define _leftparen				10
#define _leftbrace				11
#define _stringconstant			12
#define _break					13
#define _extends				14
#define _int					15
#define _readln					16
#define _while					17
#define _division				18
#define _greater				19
#define _and					20
#define _semicolon				21
#define _rightparen				22
#define _rightbrace				23
#define _booleanconstant		24
#define _class					25
#define _for					26
#define _interface				27
#define _return					28
#define _plus					29
#define _mod					30
#define _greaterequal			31
#define _or						32
#define _comma					33
#define _leftbracket			34
#define _intconstant			35
#define _id						36
#define _double					37
#define _if						38
#define _newarray				39
#define _string					40
#define _minus					41
#define _less					42
#define _equal					43
#define _not					44
#define _period					45
#define _rightbracket			46
#define _doubleconstant			47
#define _num					48
